"use client";
import type { Metadata } from "next";
import "./globals.css";
import Titlebar from "./components/Titlebar";
import { useState } from "react";
import Navbar from "./components/Navbar";
import { Toaster } from "react-hot-toast";
// import { Poppins } from "next/font/google";

// const poppins = Poppins({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"], 
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [selectMenu, setSelectMenu] = useState<string>("/");
  const [enableNav, setEnableNav] = useState<boolean>(false);

  return (
    <html lang="en">
      <body className={`flex w-screen h-screen`}>
        <Toaster position="top-right" />
        <Navbar
          enableNav={enableNav}
          selectMenu={selectMenu}
          setSelectMenu={setSelectMenu}
          setEnableNav={setEnableNav}
        />
        <div className="flex-col flex-grow">
          <Titlebar setEnableNav={setEnableNav} selectMenu={selectMenu} />
          {children}
        </div>
      </body>
    </html>
  );
}
